### PR TITLE
Small test sql fixes

### PR DESCRIPTION
**Pull request by agrawalreetika**
Small test sql fixes

### CODE REVIEW

**Review by wanglinsong — APPROVED** [review]

**Comment by ethanyzhang** [comment]
Hi @agrawalreetika , stage_4 and stage_6 intentionally included errors to do negative test
https://github.com/prestodb/pbench/blob/main/stage/stage_test.go#L26

**Comment by wanglinsong** [comment]
oh, let me revert.

**Comment by ethanyzhang** [comment]
@wanglinsong I already did

**Comment by agrawalreetika** [comment]
> Hi @agrawalreetika , stage_4 and stage_6 intentionally included errors to do negative test https://github.com/prestodb/pbench/blob/main/stage/stage_test.go#L26

Ok, thanks for the details. When I tried to check the test run locally, it was failing and I didn't notice that it was intentional.

**Pull request merged**
